In [2]:
import pandas as pd
df = pd.read_csv("../data/raw/ipl.csv")

C:\Users\disha\AppData\Local\Temp\ipykernel_36608\4077528652.py:2: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/ipl.csv")

In [4]:
print("Shape:",df.shape)

Shape: (283678, 65)

In [5]:
df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 65 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         283678 non-null  int64
 1   match_id           283678 non-null  int64
 2   date               283678 non-null  object
 3   match_type         283678 non-null  object
 4   event_name         283678 non-null  object
 5   innings            283678 non-null  int64
 6   batting_team       283678 non-null  object
 7   bowling_team       283678 non-null  object
 8   over               283678 non-null  int64
 9   ball               283678 non-null  int64
 10  ball_no            283678 non-null  float64
 11  batter             283678 non-null  object
 12  bat_pos            283678 non-null  int64
 13  runs_batter        283678 non-null  int64
 14  balls_faced        283678 non-null  int64
 15  bowler             283678 non-null  object
 16  valid_ball         283678 non-null  int64
 17  runs_extras        283678 non-null  int64
 18  runs_total         283678 non-null  int64
 19  runs_bowler        283678 non-null  int64
 20  runs_not_boundary  283678 non-null  bool
 21  extra_type         15493 non-null   object
 22  non_striker        283678 non-null  object
 23  non_striker_pos    283678 non-null  int64
 24  wicket_kind        14106 non-null   object
 25  player_out         14106 non-null   object
 26  fielders           10245 non-null   object
 27  runs_target        136510 non-null  float64
 28  review_batter      907 non-null     object
 29  team_reviewed      907 non-null     object
 30  review_decision    907 non-null     object
 31  umpire             907 non-null     object
 32  umpires_call       283678 non-null  bool
 33  player_of_match    283678 non-null  object
 34  match_won_by       283678 non-null  object
 35  win_outcome        278954 non-null  object
 36  toss_winner        283678 non-null  object
 37  toss_decision      283678 non-null  object
 38  venue              283678 non-null  object
 39  city               283678 non-null  object
 40  day                283678 non-null  int64
 41  month              283678 non-null  int64
 42  year               283678 non-null  int64
 43  season             283678 non-null  object
 44  gender             283678 non-null  object
 45  team_type          283678 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4724 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     283678 non-null  int64
 50  overs              283678 non-null  int64
 51  event_match_no     283678 non-null  object
 52  stage              283678 non-null  object
 53  match_number       283678 non-null  object
 54  team_runs          283678 non-null  int64
 55  team_balls         283678 non-null  int64
 56  team_wicket        283678 non-null  int64
 57  new_batter         13593 non-null   object
 58  power_surge_start  0 non-null       float64
 59  batter_runs        283678 non-null  int64
 60  batter_balls       283678 non-null  int64
 61  bowler_wicket      283678 non-null  int64
 62  batting_partners   283678 non-null  object
 63  next_batter        13593 non-null   object
 64  striker_out        283678 non-null  bool
dtypes: bool(3), float64(3), int64(24), object(35)
memory usage: 135.0+ MB

In [8]:
df.isnull().sum().sort_values(ascending=False)

power_surge_start    283678
team_reviewed        282771
review_batter        282771
review_decision      282771
umpire               282771
                      ...
batter_runs               0
batter_balls              0
bowler_wicket             0
batting_partners          0
striker_out               0
Length: 65, dtype: int64

In [9]:
df.nunique()

Unnamed: 0          283678
match_id              1193
date                   905
match_type               1
event_name               1
                     ...
batter_balls            74
bowler_wicket            2
batting_partners      5235
next_batter            679
striker_out              2
Length: 65, dtype: int64

In [10]:
df[['match_id', 'innings', 'batting_team', 'bowling_team', 'team_runs', 'team_wicket']].head(30)

,match_id,innings,batting_team,bowling_team,team_runs,team_wicket
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,0
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,0
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,0
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,0
6,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,0
7,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,0
8,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,0
9,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,11,0
10,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,17,0
11,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,21,0
12,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,21,0
13,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,21,0
14,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,21,0
15,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,22,0
16,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,26,0
17,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,27,0
18,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,27,0
19,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,32,0
20,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,38,0
21,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,39,0
22,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,43,0
23,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,43,0
24,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,44,0
25,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,50,0
26,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,54,0
27,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,55,0
28,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,59,0
29,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,59,0

In [11]:
df[df['match_id'] == df['match_id'].iloc[0]][
    ['match_id', 'innings', 'batting_team', 'bowling_team', 'team_runs', 'team_wicket']
].drop_duplicates()

,match_id,innings,batting_team,bowling_team,team_runs,team_wicket
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,0
6,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,0
8,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,7,0
9,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,11,0
...,...,...,...,...,...,...
219,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,79,9
220,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,80,9
221,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,81,9
223,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,82,9
224,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,82,10